#!/bin/bash

sudo pacman -S git sway swaybg swaylock swayimg vim alacritty flatpak firefox yazi blueman rofi-wayland brightnessctl fastfetch autotiling base-devel picom feh go grim slurp --noconfirm

git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si --noconfirm
cd
mv yay .yay

git clone https://www.github.com/lagantius/linux

rm ~/.bashrc
rm ~/.bash_profile
mv ~/linux/bashrc ~/.bashrc
mv ~/linux/bash_profile ~/.bash_profile
source ~/.bashrc

mkdir ~/obrázky
mkdir ~/obrázky/screenshoty
mkdir ~/obrázky/tapety

mv ~/linux/arch-pacman.png ~/obrázky/tapety

mkdir ~/.config/alacritty
mv ~/linux/alacritty ~/.config/alacritty/alacritty.toml

mkdir ~/.config/fastfetch
mv ~/linux/fastfetch ~/.config/fastfetch/config.jsonc

mkdir ~/.config/sway
mv ~/linux/sway ~/.config/sway/config

mkdir ~/.config/rofi
mv ~/linux/rofi ~/.config/rofi/config.rasi

mkdir ~/.config/gtk-3.0
mv ~/linux/gtk ~/.config/gtk-3.0/settings.ini

rm -rf ~/linux
