#!/bin/bash

sudo pacman -S git sway swaybg alacritty firefox thunar blueman rofi-wayland brightnessctl fastfetch autotiling base-devel picom feh go --noconfirm

git clone https://www.github.com/lagantius/linux

~/linux/yay
mv yay .yay

rm ~/.bashrc
rm ~/.bash_profile
mv ~/linux/bashrc ~/.bashrc
mv ~/linux/bash_profile ~/.bash_profile
source ~/.bashrc

mkdir ~/.config/wallpaper
mv ~/linux/arch-pacman.png ~/.config/wallpaper/

mkdir ~/.config/alacritty
mv ~/linux/alacritty ~/.config/alacritty/alacritty.toml

mkdir ~/.config/fastfetch
mv ~/linux/fastfetch ~/.config/fastfetch/config.jsonc

mkdir ~/.config/sway
mv ~/linux/sway ~/.config/sway/config

mkdir ~/.config/rofi
mv ~/linux/rofi ~/.config/rofi/config.rasi

rm -rf ~/linux
