#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# configs
alias ls='ls --color=auto'
alias grep='grep --color=auto'
PS1='\[\033[1;32m\][\u@\h \w] > \[\033[0m\]'
export QT_QPA_PLATFORMTHEME=qt5ct

# system aliases
alias up='~/.config/scripts/update'
alias fd='sudo mount /dev/sdc1 /mnt/usb1'
alias fdr='sudo umount /mnt/usb1'
alias slp='systemctl suspend && swaylock -k --indicator-idle-visible -i ~/obrázky/tapety/default.png'

# user aliases
alias sw='swayimg'
alias fa='fastfetch'
alias tmst='sudo -E timeshift-gtk'
alias smc='sudo MC_PROFILE_ROOT="$HOME" mc'
alias gpgkill='gpgconf --kill gpg-agent'
